### PR TITLE
Document onboarding steps

### PR DESCRIPTION
**Pull request by liangyuanruo**
Documenting the steps for a working development environment with SGID integration.

### CODE REVIEW

**Comment by fynyky** [comment]
The port in the instructions is 1338 instead of 1337. Did you change the port? If you're listening on 1338 instead of 1337 it might be that you already had an app running on 1337

**Comment by liangyuanruo** [comment]
> The port in the instructions is 1338 instead of 1337. Did you change the port? If you're listening on 1338 instead of 1337 it might be that you already had an app running on 1337

I haven't changed the port mapping so this is quite mystifying, and I am not sure if the problem is unique to my machine.

I've verified that the external port 1337 isn't in use, but external port 1338 is automatically mapped to the docker port 1337:

```sh

ogp-yuanruo@y-liang-KLVCF ~ % sudo lsof -nP -iTCP:1337 | grep LISTEN
ogp-yuanruo@y-liang-KLVCF ~ % sudo lsof -nP -iTCP:1338 | grep LISTEN
com.docke 45087 ogp-yuanruo  159u  IPv6 0x1f6f9cd3ca4b8633      0t0  TCP *:1338 (LISTEN)

ogp-yuanruo@y-liang-KLVCF ~ % docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS         PORTS                                            NAMES
0e48ae057424   freestuff_onboarding-app         "sleep infinity"         2 minutes ago   Up 2 minutes   80/tcp, 0.0.0.0:1338->1337/tcp                   freestuff_onboarding-app-1
abb5180672be   freestuff_onboarding-blobstore   "/usr/bin/docker-ent…"   2 minutes ago   Up 2 minutes   0.0.0.0:9002->9000/tcp, 0.0.0.0:9003->9001/tcp   freestuff_onboarding-blobstore-1
ecba289386f4   freestuff_onboarding-cache       "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   0.0.0.0:6380->6379/tcp                           freestuff_onboarding-cache-1
80d325864483   freestuff_onboarding-db          "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes   0.0.0.0:5433->5432/tcp                           freestuff_onboarding-db-1
```

I've also spent some time reading through Docker setup, performed a clean re-install of Docker + the Dev Environment, and tested adding dummy SGID env vars to make sure the application container can boot up properly the first time.

**Comment by liangyuanruo** [comment]
Are the steps roughly in line with what you have? If so, I'll update the instructions to use port 1337 as the external port first as it's clearly working for you, and continue investigating my own machine configuration later.

**Comment by fynyky** [comment]
Yeah its roughly what I have. Odd. I only observe the 1337-1338 problem when I accidentally have 2 instances and hence double tag the port. Maybe its because of the ngrok thing you were doing? Eitherway will merge for now

**Pull request merged**
